### ISSUE TITLE
Weather not displaying accurate temps

### ISSUE THREAD

**Issue by flatoutdodge** [ineptech/mirror#17] opened 2016-04-03 19:02 UTC
I have checked and rechecked the coordinates used and I am still not getting the correct temperatures. My current temp is off by almost 10 degrees. When I use my api key along with my coordinates on my browser, I can see the correct current temperature in the code. So it leads me to believe that the app is not pulling the correct data.

**Comment by ineptech** [comment] 2016-04-05 15:33
Hunh, that's pretty weird.  Can you send me the full url you're using, along with the correct temp and the time of day?   Does it do this all the time or just occasionally?  When I had this problem it was because I forgot the minus sign on the lattitude.

**Comment by flatoutdodge** [comment] 2016-04-06 21:12
https://api.forecast.io/forecast/f204ba8b859279829c992912a30a6781/48.31,-82.13 Those are the correct coordinates for Elyria, OH. It depends on the time of day that determines how far off it is. Currently my actual temperature (according to intellicast.com and from what I can decipher from the url) is 61º (61º | 43º) and the app is showing 53º (58º | 30º)

**Comment by ineptech** [comment] 2016-04-06 22:31
I think the problem is just a typo - according to Google Maps, Elyria OH is latitude 41.31,  not 48.31.  The coordinates you specified are about 500 miles due north, in the middle of Canada :)

**Comment by flatoutdodge** [comment] 2016-04-07 00:49
Oh, sorry, the typo was in the url in the message. I have been using 41.31 on the app. and just double-checked to make sure. The temps are still off I'm afraid.

**Comment by ineptech** [comment] 2016-04-07 15:37
Hrm.  The code is pretty simple - the url it submits looks like this:  

https://api.forecast.io/forecast/api-key/41.31,-82.13,2016-04-07T08:22:33-0800?exclude=minutely,hourly

I don't think there's any way there could be a bug screwing up the coordinates, so the only other possibility is an issue with the time or timezone.  The timezone it submits is the one your phone considers itself to be in, not necessarily the one for the latitude/longitude you enter.  Any chance your phone/tablet is set to a different timezone than GMT -4?

**Comment by flatoutdodge** [comment] 2016-04-07 20:40
The tablet is set to the correct GMT of -4. Right now the current temperature is correct but my High is off by 6º. Is the high/low data for the day or for the next 24 hours? Its really hard to tell if the temperature module is working correctly or if the temperatures are similar in another location, giving the impression that it is.

**Comment by Thamial** [comment] 2016-04-13 14:04
I got a bit different problem: My up/low are mostly correct, but current temp is off.

I tested with coordinates http://forecast.io/#/f/61.45,23.84, and got -3°c (7°c|-4°c). On the page forecast says right now is 9°c. 

Tablet is set to correct GMT +3

**Comment by thepiratejesh** [comment] 2016-05-12 00:14
Having the same problem as Thamial.

**Comment by thepiratejesh** [comment] 2016-05-12 17:14
For me, the problem had something to do with the way that the time is being entered into the URL. I fixed the problem by changing the line:

`forecastTime += "T" + new SimpleDateFormat("HH:mm:ss-0800").format(new Date());`

to:

`forecastTime += "T" + new SimpleDateFormat("HH:mm:ss").format(new Date());`

**Comment by ineptech** [comment] 2016-05-20 15:29
Argh!  Thank you @thepiratejesh, you're right, I was hard-coding GMT-0800 in to the url.  Sorry it took me so long to look at this, been a busy time at home but I will get this checked in ASAP.

**Closed as completed** 2016-05-20 15:42 UTC
