### ISSUE TITLE
web page module resizes 

### ISSUE THREAD

**Issue by mmveets** [ineptech/mirror#14] opened 2016-02-21 16:29 UTC
On my Nexus 7, the web page module config resizes after I edit a URL, and the button to edit the URL is no longer shown

**Comment by ineptech** [comment] 2016-02-21 18:12
Weird.  Can you reproduce that reliably?  Did the display change from portrait to landscape or back during this?  That kind of messes the display up a bit.  Also note that adding a url removes the "add url" button (because it only accepts one) but then removing the existing one should bring back the "add url" button.

**Comment by mmveets** [comment] 2016-02-21 22:09
I see no button to remove the URL. It's always in portrait mode. And it reproduces every time.   I could only add one URL. Maybe because it's a long URL? I see two lines of it, and then the box ends. I could send a screen capture if it would help.

**Comment by ineptech** [comment] 2016-04-09 00:08
Should be fixed now.

**Closed as completed by ineptech** 2016-04-09 00:08 UTC

**Comment by mmveets** [comment] 2016-04-09 01:05
```
                                                                                  Thanks!What a coincidence - I just figured out today a way that I can use the web module for a quote of the day (because I don't know anything about programming) http://api.forismatic.com/api/1.0/?method=getQuote&format=text&lang=enBest regards, Mike‎                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: ineptechSent: Friday, April 8, 2016 7:08 PMTo: ineptech/mirrorReply To: ineptech/mirrorCc: mmveetsSubject: Re: [ineptech/mirror] web page module resizes  (#14)Should be fixed now.
```

—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by ineptech** [comment] 2016-04-10 22:25
Hey, cool!  Thanks for sending me that, I'm going to make it the default URL for the web module.

**Comment by mmveets** [comment] 2016-04-11 14:46
You're welcome.  I realized that your module updates every minute, so it's actually a quote-of-the-minute with that link.  I hope they don't get pissed at the increased traffic and cut it off.  If you're still working on the app, then maybe an adjustable update frequency?
Here's another api I found for a quote-of-the-day.  It will return output in xml or JSON.  I don't know how to transform those to plain text, which is why I found the other one at forismatic.
Quotes API from They Said So

|
|
|
|

   |

  |
|  
|   |  
Quotes API from They Said So
 The They Said So website holds an extensive database with over a million quotes from a hundred thousand differen...  |   |

  |

  |

```
  From: ineptech <notifications@github.com>
```

 To: ineptech/mirror mirror@noreply.github.com 
Cc: mmveets mmveets@yahoo.com
 Sent: Sunday, April 10, 2016 5:25 PM
 Subject: Re: [ineptech/mirror] web page module resizes (#14)

Hey, cool! Thanks for sending me that, I'm going to make it the default URL for the web module.—

**Comment by mmveets** [comment] 2016-08-19 18:43
Hi, Nick.Any plans to return to this app?  The ability to have it auto-launch would be very, very helpful.  I copied the GitHub discussion below.  I haven't done any coding since Fortran about 25 years ago, so I'm pretty much hopeless to change it on my own.  :-)
Best regards,Mike

feature request: don't start with config as default #15 Open mmveets opened this issue on Feb 21 · 3 commentsLabels

@mmveets @ineptech @FynnZW@mmveetsmmveets commented on Feb 21first : great app!I'd love to be able to use this completely hands-free, and to be able to give an occasional Google Now voice request. But when going back to the app ("ok, Google, open Magic Mirror) it starts at the config screen and requires a touch to press "save"@ineptechOwnerineptech commented on Feb 21I've thought of this but am not sure how to implement it. How would someone launch the config screen? A hidden/invisible button seems like poor design - people will forget where it is. Maybe it should launch with config, but automatically save if there's no user activity for 10 seconds?@mmveetsmmveets commented on Feb 21That sounds perfect. Even a long delay like a minute or two would be fine.@FynnZWFynnZW commented on Feb 28+1, would be nice.But at least after a minute, and maybe a notification the app is about to start without saving

```
  From: Mike M <mmveets@yahoo.com>
```

 To: ineptech/mirror reply@reply.github.com 
 Sent: Monday, April 11, 2016 9:46 AM
 Subject: Re: [ineptech/mirror] web page module resizes (#14)

You're welcome.  I realized that your module updates every minute, so it's actually a quote-of-the-minute with that link.  I hope they don't get pissed at the increased traffic and cut it off.  If you're still working on the app, then maybe an adjustable update frequency?
Here's another api I found for a quote-of-the-day.  It will return output in xml or JSON.  I don't know how to transform those to plain text, which is why I found the other one at forismatic.
Quotes API from They Said So

|
|
|
|

  |

  |
|  
|   |  
Quotes API from They Said So
 The They Said So website holds an extensive database with over a million quotes from a hundred thousand differen...  |   |

  |

  |

```
  From: ineptech <notifications@github.com>
```

 To: ineptech/mirror mirror@noreply.github.com 
Cc: mmveets mmveets@yahoo.com
 Sent: Sunday, April 10, 2016 5:25 PM
 Subject: Re: [ineptech/mirror] web page module resizes (#14)

Hey, cool! Thanks for sending me that, I'm going to make it the default URL for the web module.—
